### ISSUE TITLE
Close button and modal transition mismatch

### ISSUE THREAD

**Issue by terenc3** [tylercrumpton/crump-bingo#1]
When closing the modal it disappears immediately but the close button has a 200ms transition. I would either add a transition to the card as well or restrict the transition to only affect the filter property (i guess that is the reason it was added).

P.S. I hope you saw the eclipse and can check that card 🙂

**Comment by tylercrumpton** [comment]
Good catch! Fixed up the animations a little, and there was a bit of a graphical glitch with the different fading times, so that's been cleaned up as well, so it feels a bit cleaner now. Thanks!

(And we kinda got to see the eclipse! Super cloudy in Rochester, but it was still super super cool!)
